### ISSUE TITLE
Why did you choose to use RouterOutputs over @primsa/client ?

### ISSUE THREAD

**Issue by acharlop** [jherr/notetaker#2]
Thanks for all the awesome material, you rock!!

Just one question on this repo/tutorial if you look at https://github.com/jherr/notetaker/blob/main/src/pages/index.tsx#L29

These type definitions are exactly the same as far as I can tell. So just wondering why you picked one over the other? To show off TRPC over Prisma?

```
import type { Topic } from '@prisma/client'

type Topic = RouterOutputs['topic']['getAll'][0]
```

**Comment by jherr** [comment]
Because I'm making the request from the client with TRPC. So yes, in this case the two are the same, but if the TRPC layer was doing some type of permutation then I would get that and not the direct Prisma type.

**Comment by acharlop** [comment]
Thanks for the clarification and all the good content 🙏
