### ISSUE TITLE
Add missing instrutions for Windows;; possible age resitriton on YouTube; pause after entering code in future tutorials.

### ISSUE THREAD

**Issue by AStarCale** [jherr/notetaker#3]
#

## Problem

The tutorial is great, I appreciate how it's not super long and doesn't have stuff I don't need to get my Markdown Next.JS project going, but the instructions only work right on Mac and you did not include the steps to use the production Github OAuth, and you are pushing out the dev GitHub OAuth API keys.

My 14-year-old son tried to watch the video on his account and the would not show up when he was logged in, but we were able to watch it using another browser that was not signed in with the same link, so it looks like the videos is wrongfully age-restricted.

When you enter code you (or rather your editor) jump very quickly after you enter code to other parts of the code, which reduces video length and ad revenue.  Maybe you could redo the video using the new Next.JS app directory?

## Solution

Add those missing instructions to the `~/ReadMe.md` to add the GitHub dev OAuth keys to the .env file and to use the production GitHub OAuth account APIs keys in Vercel.

For the next tutorial, it would help a lot if you pause for a few seconds after you input the code so it's easier to pause the video and type in what you typed in, and you would get more ad revenue from the longer video.

**Comment by jherr** [comment]
Thank you for reaching out and please say hello and thank you for watching to your son. About the age ranking, I set my videos like this:

<img width="714" alt="Screenshot 2023-05-28 at 5 48 11 PM" src="https://github.com/jherr/notetaker/assets/22392/c26aea82-c3f3-4bd2-b44e-17f2dced37dc">

They are not _made_ for children, but they are always appropriate for viewing by children. I never use profanity or talk about adult subjects. Though I think in one video a long time ago I referenced beer.  I'm not sure what your son's YouTube settings might be, it could be an issue that his settings have restricted him to only videos specifically made for children.

I'll take your feedback about pausing the video, thank you for that. Though I don't think long videos mean higher ad revenue. Ad revenue is based on views and longer videos get less views.

If you figured out the GitHub OAuth flow with your son feel free to PR this repo with a Readme.MD and I would happily approve it.
